---
- name: Cambiar al directorio ~/.awx/awxcompose
  shell: cd ~/.awx/awxcompose
  
- name: Run migrations in task container
  shell: docker compose run --rm --service-ports task awx-manage migrate --no-input
  args:
    chdir: "~/.awx/awxcompose"


- name: Wait for next task
  wait_for:
    timeout: 10
